"""Add Atributo, Objeto and Valor to database

Revision ID: 40a2db647fd9
Revises: 
Create Date: 2024-12-01 20:40:55.271849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a2db647fd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objeto_atributo',
    sa.Column('objeto_id', sa.Integer(), nullable=False),
    sa.Column('atributo_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('maximo', sa.Integer(), nullable=True),
    sa.Column('minimo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atributo_id'], ['atributo.id'], ),
    sa.ForeignKeyConstraint(['objeto_id'], ['objeto.id'], ),
    sa.PrimaryKeyConstraint('objeto_id', 'atributo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objeto_atributo')
    op.drop_table('objeto')
    op.drop_table('atributo')
    # ### end Alembic commands ###
